---
driver:
  network:
  - ["private_network", {ip: "192.168.33.44"}]
  synced_folders: [["/vagrant/binaries", "/vagrant/binaries"]]
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[df_box_mesos::default]
    attributes: 